apiVersion: apps/v1
kind: Deployment
metadata:
  name: mamadou-memApp
  labels:
    app: memApp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: memApp

template:
  metadata:
    labels:
      app: memApp
  spec:
    containers:
      - name: memApp
        image: mbenguep/memoire
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1